[package]
name = "flow"
version = "0.3.0"
edition = "2021"
publish = true
[lib]
path = "src/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
