[package]
name = "flow-example"
version = "0.1.0"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flow = { path = "../flow" }
anyhow = "1.0.69"
tokio = {version = "1.26.0", features = ["full"] }
